# Generated by Django 5.2.4 on 2025-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
