# Generated by Django 5.2.4 on 2025-08-05 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameBasics',
            fields=[
                ('nconst', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('primary_name', models.CharField(max_length=255)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('primary_profession', models.CharField(max_length=255, null=True)),
                ('known_for_titles', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleBasics',
            fields=[
                ('tconst', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title_type', models.CharField(max_length=20)),
                ('primary_title', models.CharField(max_length=500)),
                ('original_title', models.CharField(max_length=500)),
                ('is_adult', models.BooleanField()),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TitleRatings',
            fields=[
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='imdb.titlebasics')),
                ('average_rating', models.FloatField()),
                ('num_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TitleAkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('title_text', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=20, null=True)),
                ('language', models.CharField(max_length=20, null=True)),
                ('types', models.CharField(max_length=100, null=True)),
                ('attributes', models.CharField(max_length=100, null=True)),
                ('is_original_title', models.BooleanField(null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.titlebasics')),
            ],
        ),
        migrations.CreateModel(
            name='TitlePrincipals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=255, null=True)),
                ('characters', models.CharField(max_length=500, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.namebasics')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.titlebasics')),
            ],
        ),
        migrations.CreateModel(
            name='TitleCrew',
            fields=[
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='imdb.titlebasics')),
                ('directors', models.ManyToManyField(related_name='directed_titles', to='imdb.namebasics')),
                ('writers', models.ManyToManyField(related_name='written_titles', to='imdb.namebasics')),
            ],
        ),
        migrations.CreateModel(
            name='TitleEpisode',
            fields=[
                ('tconst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='imdb.titlebasics')),
                ('season_number', models.IntegerField(null=True)),
                ('episode_number', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='imdb.titlebasics')),
            ],
        ),
    ]
