# Generated by Django 5.2.4 on 2025-08-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleakas',
            name='title_text',
            field=models.CharField(max_length=700),
        ),
    ]
