# Generated by Django 5.2.4 on 2025-08-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_alter_titleakas_title_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleakas',
            name='title_text',
            field=models.CharField(max_length=1000),
        ),
    ]
