# Generated by Django 5.2.4 on 2025-08-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0004_alter_titleakas_title_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titleakas',
            old_name='title',
            new_name='tconst',
        ),
        migrations.RenameField(
            model_name='titlecrew',
            old_name='title',
            new_name='tconst',
        ),
        migrations.RenameField(
            model_name='titleprincipals',
            old_name='name',
            new_name='nconst',
        ),
        migrations.RenameField(
            model_name='titleprincipals',
            old_name='title',
            new_name='tconst',
        ),
        migrations.RenameField(
            model_name='titleratings',
            old_name='title',
            new_name='tconst',
        ),
    ]
