# Generated by Django 5.2.4 on 2025-08-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0005_rename_title_titleakas_tconst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namebasics',
            name='known_for_titles',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='namebasics',
            name='primary_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='namebasics',
            name='primary_profession',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='titlebasics',
            name='genres',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='titlebasics',
            name='original_title',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='titlebasics',
            name='primary_title',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='titlebasics',
            name='start_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='titlebasics',
            name='title_type',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
