"""
📄 TEMPLATE CONFIG FILE

This is a template file for sensitive configuration values like database credentials and Django's secret key.

➡️ INSTRUCTIONS:
1. **DO NOT EDIT THIS FILE DIRECTLY.**
2. Copy this file and rename the copy to `config.py`.
3. Fill in the values in `config.py` with your local or production-specific credentials.
4. Keep `config.py` in the same directory as `settings.py`.
5. Ensure `config.py` is listed in `.gitignore` so it won't be committed to version control.

This pattern helps keep your credentials secure and your repository clean.
"""

DATABASE_NAME = ""
DATABASE_USER = "postgres"
DATABASE_PASSWORD = ""
DATABASE_HOST = ""
DATABASE_PORT = "5432"

# Django's secret key (used for security, must be unique and kept secret)
# Generate with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = ''

# Debug mode: Set to True during development only. Set to False in production.
DEBUG = False